server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://ec2-54-180-123-82.ap-northeast-2.compute.amazonaws.com:3306/springweb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

payment:
  toss:
    test_client_api_key: test_ck_ex6BJGQOVDb1xavAXnNR8W4w2zNb
    test_secrete_api_key: test_sk_ma60RZblrqoMxPQzAEkx3wzYWBn1
    success_url: "http://localhost:9090/api/v1/payments/toss/success"
    fail_url: "http://localhost:9090/api/v1/payments/toss/fail"