server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    include: oauth
  config:
    import: classpath:application-api.yml, classpath:application-oauth.yml, classpath:application-swagger.yml
  datasource:
    url: jdbc:mysql://localhost:3306/AWS
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: khs04140
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
