server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    include: oauth
  config:
    import: classpath:application-api.yml
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/jpa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root} # 기본값으로 root를 사용하도록 설정
    password: ${MYSQL_PASSWORD:khs04140} # 기본값으로 khs04140을 사용하도록 설정

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
